<div class="row">
    <div class="col-sm-6">
        <?php
        echo $this->form()->openTag($form);
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            <?php echo $this->formRow($form->get('name')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            <?php echo $this->formRow($form->get('price')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            <?php echo $this->formRow($form->get('description')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-5">
        <div class="form-group">
            <?php echo $this->formRow($form->get('submit')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<table class="table table-striped table-bordered">
    <thead class="thead-grid-pesquisa">
        <tr>
            <th class="table-id">ID</th>
            <th class="table-name">NAME</th>
            <th class="table-price">PRICE</th>
            <th class="table-description">DESCRIPTION</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($data as $item): ?>
            <tr>
                <td><?php echo $this->escapeHtml($item->getId()); ?></td>
                <td><?php echo $this->escapeHtml($item->getName()); ?></td>
                <td><?php echo $this->escapeHtml($item->getPrice()); ?></td>
                <td><?php echo $this->escapeHtml($item->getDescription()); ?></td>
            </tr>
        <?php endforeach; ?>
</table>